### ISSUE TITLE
项目结构介绍调整

### ISSUE THREAD

**Issue by goddlts** [lipengzhou/vuejs-tutorial#1]
项目结构介绍，让此处高亮

├── src  源代码
│   ├── assets  存放一些静态资源，例如 css、img、fonts
│   ├── components  业务组件
│   ├── router
│   ├── └── index.js  路由配置文件
│   ├── App.vue  根组件
│   └── main.js  项目启动入口文件

**Comment by lipengzhou** [comment]
Thank you for your offer, has been updated.
